[project]
name = "dev-sm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1,<0.142.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
dev-sm = "dev_sm:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pydantic-settings>=2.14.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.1",
    "taskipy>=1.14.1",
]

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'

[tool.taskipy.tasks]
lint = 'ruff check'
pre_format = 'ruff check --fix'
format = 'ruff format'
run = 'fastapi dev dev_sm/app.py'
pre_test = 'task lint'
test = 'pytest -s -x --cov=dev_sm -vv'
post_test = 'coverage html'
